# Generated by Django 4.1.3 on 2022-11-10 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TripDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.IntegerField()),
                ('vehicle_id', models.IntegerField()),
                ('customer_id', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('cargo_tonnage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cargo_type', models.CharField(choices=[('pick_up_point', 'pick_up_point'), ('drop_off_point', 'drop_off_point')], default='pick_up_point', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('done_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
